### ISSUE TITLE
Internal Server Error on 10,000 offset

### ISSUE THREAD

**Issue by ElusiveMind** [usgpo/api#77]
I understand keeping the page set small, but the offset is also causing 500 errors. Here is a broken URL:

https://api.govinfo.gov/collections/BILLS/1970-01-01T00%3A00%3A00Z?pageSize=100&offset=10000&api_key=xxxxxx

This is a dealbreaker bug for a lot of api calls.

**Comment by jonquandt** [comment]
Hi, @ElusiveMind - thanks for the feedback. 

Are you trying to get all bills published since 1970? 

The _collections_ service mimics our sitemaps to let users pull the latest data for a given collection by the date-time it was added to or updated on govinfo. Since we have periodically had to do complete data republishing in the past several years, you shouldn't need to use anything before 2019 for the startDate. The primary use case for the _collections_ service would be to crawl for new and updated BILLS that you would extract on a regular basis, so you could have rolling calls that check for new BILLS since your last check.

You may be interested in using our [published service](https://github.com/usgpo/api#published-service) instead. This allows you to get a list of packages by the date it was issued. So, a BILL from the Clinton era would show up in a published request in 1996, while the same bill may show up in a _collections_ request for 2020, because that was the last time it was published/updated on the govinfo system - possibly to update the metadata, regenerate the pdf, or just to reindex within our search engine.

You can also use some specific parameters to make this easier to limit down -- by `congress` or `docClass`, for example. 

For example, you could grab a list of all 8,339 BILLS packages published in 2001:
https://api.govinfo.gov/published/2001-01-01/2001-12-31?offset=0&pageSize=100&collection=BILLS&api_key=DEMO_KEY

Senate bills for the same period:
https://api.govinfo.gov/published/2001-01-01/2001-12-31?offset=0&pageSize=100&collection=BILLS&docClass=s&api_key=DEMO_KEY

I hope this is helpful, but please let me know if there's a way that we can better document the purposes for these two services.

**Comment by ElusiveMind** [comment]
I am trying to pull all of the bills that are available.

I am keeping a "last modified" variable in my database to track this. When it starts, however, it starts at 0 which is 1970.

When trying to crawl through pages of 100 documents, I increase the offsets to get more documents.  Is it necessary to break this up by date? It is noteworthy that when retrieving granules, the offset=10000 problem does not exist and I am able to pull all granules up to my API limit.

Thoughts?

**Comment by ElusiveMind** [comment]
I used an above example to pull USCOURT opinions for 2020-06-14 to 2020-06-15

https://api.govinfo.gov/collections/USCOURTS/2020-06-14T00:00:00Z/2020-06-15T00:00:00Z?offset=0&pageSize=100&api_key=<CODE>

The record set is > 1.2 million records. I'll see if I can used the published way of pairing down the records, I just though maybe the 500 error thrown by offsets > 10,000 might have been a bug

**Comment by jonquandt** [comment]
@ElusiveMind  - yes, the published endpoint should probably help with that. There are infrequent times when we need to do a bulk update of large amounts of content -- the time period you mention in your last comment was related to a reindexing activity on our new infrastructure. that would mean that nearly all the USCOURTS packages across many years of actual issuance were republished/updated on govinfo within a short time period.

Specifically for courts, I am looking to add a `courtCode` parameter to both the **collections** and **published** endpoints to help narrow these down.

As for the granules, there are only a limited number of packages that have that many granules -- I believe it is primarily limited to the HOB and CRI packages. 

The **published** endpoint also includes a ModifiedSince parameter, which allows you to check for packages within your original request that have been modified since a particular time -- provides the published endpoint with some limited crossover functionality of the collections request. 

https://api.govinfo.gov/published/2001-01-01/2001-12-31?offset=0&pageSize=100&collection=BILLS&modifiedSince=2021-02-01T00:00:00Z&api_key=DEMO_KEY

**Comment by ElusiveMind** [comment]
@jonquandt - Thanks much for the info. FWIW, I also added the published endpoint to the gov-info project for PHP so that has helped a lot.  Once you make add the parameters, I can update the PHP library I am using for it:

Original
https://github.com/cnizzardini/gov-info

My Fork:
https://github.com/ElusiveMind/gov-info

**Comment by jonquandt** [comment]
@ElusiveMind  - I have added the following issue to document and track the new parameters. 
https://github.com/usgpo/api/issues/79

**Comment by jonquandt** [comment]
@ElusiveMind  - ok if I close this issue, as we're going to address the USCOURTS use case with #79?

**Comment by ElusiveMind** [comment]
Yep. Sure can.
